version: '2'

services:


  browser-load:
    image: public.ecr.aws/w3n5a5m8/adfinmod_loadgen_pre:latest
    container_name: browser-load
    env_file: application.env
    environment:
      - ENABLE_BROWSER_LOAD=1
      - ENABLE_APPROVAL_LOAD=0
      - ENABLE_POLICY_LOAD=0
      - ENABLE_LOAN_LOAD=0
    restart: always

  approval-load:
    image: public.ecr.aws/w3n5a5m8/adfinmod_loadgen_pre:latest
    container_name: approval-load
    env_file: application.env
    environment:
      - ENABLE_BROWSER_LOAD=0
      - ENABLE_APPROVAL_LOAD=1
      - ENABLE_POLICY_LOAD=0
      - ENABLE_LOAN_LOAD=0
    restart: always

  loan-load:
    image: public.ecr.aws/w3n5a5m8/adfinmod_loadgen_pre:latest
    container_name: loan-load
    env_file: application.env
    environment:
      - ENABLE_BROWSER_LOAD=0
      - ENABLE_APPROVAL_LOAD=0
      - ENABLE_POLICY_LOAD=0
      - ENABLE_LOAN_LOAD=1
    restart: always

